CREATE TABLE IF NOT EXISTS items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 0,
    category TEXT,
    expiry_date DATE, --賞味期限
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);